### ISSUE TITLE
grafana jaeger and loki screenshots still show old namespaces

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-website#1001]
### What happened?

See: https://kuma.io/docs/1.8.x/explore/observability/#configuring-grafana in practice the urls should refer to `mesh-observability` not `kuma-tracing` and `kuma-logging`

**Comment by kleinfreund** [comment]
I have a local environment with Grafana running, but I don’t know how to login to the Grafana UI.

**Comment by lahabana** [comment]
No only from 1.7.x sorry this should have been in the issue
