### ISSUE TITLE
Gateway api docs should reuse demo app

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-website#1003]
### Description

THe demo app is something users are familiar with and probably already run. We should reuse this as an example of the Gatewa

**Comment by michaelbeaumont** [comment]
@lahabana Is this not already done? `MeshGatewayRoute`s already refer to demo-app services

**Comment by lahabana** [comment]
That was a quick issue :) (I went fishing on old issues so yes seems like you fixed both already :) )
