### ISSUE TITLE
[Replatform] /robots.txt, /sitemap.xml, and /releases.json is missing

### ISSUE THREAD

**Issue by kleinfreund** [kumahq/kuma-website#1061]
### What happened?

We’re missing the following documents:

- [x] https://kuma.io/robots.txt (compare: https://deploy-preview-1056--kuma.netlify.app/robots.txt) https://github.com/kumahq/kuma-website/pull/1067
- [x] https://kuma.io/sitemap.xml (compare: https://deploy-preview-1056--kuma.netlify.app/sitemap.xml) https://github.com/kumahq/kuma-website/pull/1067
- [x] https://kuma.io/releases.json (compare: https://deploy-preview-1056--kuma.netlify.app/releases.json) https://github.com/kumahq/kuma-website/pull/1066
- [ ] https://kuma.io/images/docs/manifest.json (compare: https://deploy-preview-1056--kuma.netlify.app/images/docs/manifest.json)
- [x] https://kuma.io/preview.sh (compare: https://deploy-preview-1056--kuma.netlify.app/preview.sh) https://github.com/kumahq/kuma-website/pull/1065

They all used to be generated from

https://github.com/kumahq/kuma-website/blob/584d4f5e0334a951000c3d8215bc3be6fcf7869f/docs/.vuepress/config.js#L312-L342

---

robots.txt should have:

```
User-agent: *
Disallow: /latest_version
Disallow: /latest_version.html

Sitemap: https://kuma.io/sitemap.xml
```

releases.json should contain this kind of data:

```json
[
  "1.1.0",
  "1.1.1",
  "1.1.2",
  "1.1.3",
  "1.1.4",
  "1.1.5",
  "1.1.6",
  "1.2.0",
  "1.2.1",
  "1.2.2",
  "1.2.3",
  "1.3.0",
  "1.3.1",
  "1.4.0",
  "1.4.1",
  "1.5.2",
  "1.6.2",
  "1.7.2",
  "1.8.1",
  "1.5.0"
]
```

**Comment by mheap** [comment]
PRs open for all of the above. We don't need `manifest.json` as we don't expect the Kuma site to be installed as a PWA
