### ISSUE TITLE
[Replatform] Variable interpolation not working in all code blocks

### ISSUE THREAD

**Issue by kleinfreund** [kumahq/kuma-website#1064]
### What happened?

Example: https://kuma.io/docs/dev/installation/kubernetes/

Some code blocks are rendered like this

```
ln -s kuma-{{ $page.latestVersion }}/bin/kumactl /usr/local/bin/kumactl
```

where `{{ $page.latestVersion }}` should be interpolated.

**Comment by fabianrbz** [comment]
@mheap should we close this one?

**Comment by kleinfreund** [comment]
@fabianrbz No as this isn’t resolved. The same page as referenced in the original issue shows:

```ln -s kuma-{{ page.latest_version }}/bin/kumactl /usr/local/bin/kumactl```

**Comment by mheap** [comment]
That's my mistake. It shouldn't be wrapped in `raw` tags (not sure how they got there!)
