### ISSUE TITLE
Sidebar doesn't scroll independently

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-website#1087]
### Description

Go to:https://kuma.io/docs/1.8.x/policies/proxy-template/ and open policies in the sidebar.

See the sidebar is longer than your window size (maybe reduce your browser height to achieve this).
You need to scroll the content to see the bottom of the sidebar even though there's a scrollbar on the sidebar

See screenshot:

<img width="2447" alt="image" src="https://user-images.githubusercontent.com/702355/198227035-f963d767-ea8c-4d27-929e-7393bc4ae88b.png">

This used to exist before it's not new from the replatform

**Comment by slonka** [comment]
@lahabana seems to not be a problem any more, I can independently scroll sidebar (when hover) and content. Can you confirm and close this if that's the case for you as well?

**Comment by slonka** [comment]
Still an issue (sorry for noisy comments / reopening, misunderstood the problem).

**Comment by lahabana** [comment]
Duplicate of #1321
