### ISSUE TITLE
Broken HTML on multiple pages

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma-website#1102]
### What happened?

![image](https://user-images.githubusercontent.com/2753650/199027271-14ea2bf7-9e7d-40b1-826a-31139005c98e.png)

There is broken HTML displayed on this page https://kuma.io/docs/1.8.x/policies/retry/#http . I think we should grep the whole website and look for HTML tags (`<div>`, `<p>` etc.) because this might have happened in more than one place.

**Comment by slonka** [comment]
Also this

![image](https://user-images.githubusercontent.com/2753650/199032099-4902c12b-e8f1-47a9-8930-c211de17dea9.png)

**Comment by fabianrbz** [comment]
I'll take a look at the broken html.
The fix for the duplicated/old syntax  tips is [here](https://github.com/kumahq/kuma-website/pull/1106)

**Comment by slonka** [comment]
Changed the description because it's broken on multiple pages, the next one I found:

https://kuma.io/docs/1.8.x/security/api-server-auth/#signing-key-rotation

<img width="990" alt="image" src="https://user-images.githubusercontent.com/2753650/199673924-9d82eddb-9b9a-473a-bbcd-bbf24996b0de.png">

(notice <div> at the bottom)

**Comment by fabianrbz** [comment]
@slonka I fixed all occurrences of this issue in the PR. 
These are the files that were affected:

- app/docs/1.1.x/policies/retry.md 
- app/docs/1.2.x/policies/retry.md
- app/docs/1.3.x/policies/retry.md
- app/docs/1.4.x/policies/retry.md
- app/docs/1.5.x/policies/retry.md
- app/docs/1.6.x/policies/retry.md
- app/docs/1.7.x/policies/retry.md 
- app/docs/1.8.x/policies/retry.md 
- app/docs/dev/policies/retry.md

It was an issue with code snippets and some liquid tags not being properly indented inside numbered lists
