### ISSUE TITLE
Tabs plugin seems to be broken with lists and indentation

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma-website#1127]
### What happened?

Placing a `tabs` plugin inside a list with indentation seems to break. If you look at the code in this PR

https://github.com/kumahq/kuma-website/pull/1126/files#diff-3f84c7c84b08f0cdbfdd2a7220f068c6163191e0f9ee20c5e37d0909d23913b4R65-R84

and a preview [here](https://deploy-preview-1126--kuma.netlify.app/docs/dev/security/api-server-auth/#admin-user-token), clicking on the "wget" tab will 

![image](https://user-images.githubusercontent.com/2753650/199691377-abd80ff7-8917-440d-96e5-3c54d66fc5a5.png)

make the whole thing disappear

![image](https://user-images.githubusercontent.com/2753650/199691438-b0a6bed8-e751-4675-b65c-851c811fa298.png)

The numeration is also broken.

If I remove the indent like so:

![image](https://user-images.githubusercontent.com/2753650/199691545-d030e102-d257-49f1-becc-7fcc9cebf66a.png)

and restart `make run` (which is another issue)

![image](https://user-images.githubusercontent.com/2753650/199691708-3409748c-50b0-423b-8de9-db2ef7bac888.png)

the tabs will work but the numeration is still broken.

**Comment by fabianrbz** [comment]
@slonka this is the same issue described [here](https://github.com/kumahq/kuma-website/pull/1126), adding `indent` to those should fix it. I'll take a look at the docs and open a PR with a fix
