### ISSUE TITLE
Document new universal on k8s mode

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma-website#1231]
### Description

Do we want to document that or should this be undocumented for now? YES

**Comment by slonka** [comment]
@johnharris85 or @lahabana - should this be part of https://kuma.io/docs/dev/production/cp-deployment/multi-zone/ or a separate page? 

Side note: "The global control plane must run on a dedicated cluster, and cannot be assigned to a zone" is no longer true this must change either way :)

**Comment by lahabana** [comment]
Yes I'd add this as a new tab: "Universal on Kubernetes"
