### ISSUE TITLE
Document MeshGatewayInstance resource better

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma-website#1265]
### Description

When I was doing a review of https://github.com/kumahq/kuma/pull/6348 I faced an issue where I tried to find the allowed schema for `serviceTemplate` configuration. The only place where it's mentioned in our documentation is [here](https://kuma.io/docs/2.1.x/explore/gateway/#usage-1).

This issue was also mentioned at least once in slack discussion not related with my review.

**Comment by michaelbeaumont** [comment]
Done: https://kuma.io/docs/2.3.x/policies/meshgatewayinstance/
