### ISSUE TITLE
Diagram and explanation of iptables rules

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma-website#1287]
### Description

While we have a description of how to configure iptables and that it's "Redirect all the relevant inbound, outbound and DNS traffic to the Kuma data plane proxy", we don't have a deep-dive explanation of how our rules work.

It would be great to have an explanation of the rules as well as a diagram of DNS interception (because it has a few hops).

Requested by Mani Hosseini

**Comment by lahabana** [comment]
> Triage: we may have some internal information we can bubble up here.

**Comment by slonka** [comment]
@dascole do you need any help with this? :)
