### ISSUE TITLE
Update MeshGateway Policy Support

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma-website#1296]
### Description

- Some new policies are lacking MeshGateway from their support tables so we should ensure they're included everywhere (even if unsupported).
- [This page](https://kuma.io/docs/2.1.x/explore/gateway/) needs to be updated with the new policies.

**Comment by michaelbeaumont** [comment]
@johnharris85 @lahabana do we actually the table listing each policy with its support? Each policy should cover its gateway support IMO

**Comment by michaelbeaumont** [comment]
Closing this as the structure of the docs has changed significantly and we've added support for new policies to gateways
