### ISSUE TITLE
The "Argo CD" section of the docs appears to be missing in 2.2

### ISSUE THREAD

**Issue by brentos** [kumahq/kuma-website#1319]
### What happened?

In 2.1 there was a section in the docs under `Install->Helm->Argo CD` that appears to be missing in the 2.2 docs.

**Comment by slonka** [comment]
It is now in https://kuma.io/docs/2.5.x/production/cp-deployment/kubernetes/#argo-cd (also in [2.4](https://kuma.io/docs/2.4.x/production/cp-deployment/kubernetes/#argo-cd) but I can't see up until 2.3) - @cloudjumpercat can you make sure it's available for all supported versions?

**Comment by slonka** [comment]
> Just to confirm, you want that Kubernetes page with the Argo CD version to show for 2.3-1.2?

Our active releases are listed here https://github.com/kumahq/kuma/blob/master/active-branches.json so we're missing this page for 2.2 and 2.3

**Comment by lukidzi** [comment]
2.2 is not supported anymore. ArgoCD docs are now available `Kuma in production -> Control plane deployment -> Kubernetes` https://kuma.io/docs/2.9.x/production/cp-deployment/kubernetes/#argo-cd
