### ISSUE TITLE
Scroll menu on docs sidebar too tall

### ISSUE THREAD

**Issue by paullryan** [kumahq/kuma-website#1321]
### What happened?

Given the header size the .sidebar > .sidebar-links menu is larger than the visible area, 100vh assumes that it's the size of the whole screen when it's really 100vh - (size of headers) or approximately 85vh. At it's current 100vh when it overflows the screen you cannot scroll to the bottom.  

You can see this issue by going to https://kuma.io/docs/2.2.x/policies/meshloadbalancingstrategy/ and trying to scroll to the bottom of the sidebar menu.

I have tried 85vh and it appears to work however this should be tested with more screens. A more ideal path would be to use a calculation for this height.

**Comment by lahabana** [comment]
xref #1241
