### ISSUE TITLE
Make policy `.json` source for schema plugin configurable

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma-website#1325]
> Should we make this path configurable in the tag? Feels like we may need to have something different for KM. (We can probably do this in a follow up though)

_Originally posted by @lahabana in https://github.com/kumahq/kuma-website/pull/1289#discussion_r1182375434_

Ideally it's configurable once and effective for every usage of the plugin

**Comment by lahabana** [comment]
This works fine now
