### ISSUE TITLE
Broken autogenerated schema for some policies

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma-website#1333]
### What happened?

- https://kuma.io/docs/dev/policies/meshhealthcheck/#all-policy-options
- https://kuma.io/docs/dev/policies/meshhttproute/#all-policy-options
- https://kuma.io/docs/dev/policies/meshretry/#all-policy-options
- https://kuma.io/docs/dev/policies/meshloadbalancingstrategy/#all-policy-options

**Comment by michaelbeaumont** [comment]
Fixed upstream: https://github.com/BrianWendt/json-schema-md-doc/pull/18
