### ISSUE TITLE
Document delta kds flag

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma-website#1351]
### Description

This was missed in 2.2 I think.

**Comment by jakubdyszkiewicz** [comment]
> It's missing here https://github.com/kumahq/kuma/blob/master/pkg/config/app/kuma-cp/kuma-cp.defaults.yaml let's see if can write a test to avoid this problem in the future.

**Comment by lukidzi** [comment]
done by https://github.com/kumahq/kuma/pull/7085 and also set as default
