### ISSUE TITLE
Document --exclude-inbound-ports=22 when installing transparent-proxy

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma-website#1375]
### What happened?

It may happen when installing transparent proxy on some external VM, that you'll loose SSH connection afterwards. You can exclude SSH port from transparent proxy by using `--exclude-inbound-ports` flag (i.e. `kumactl install transparent-proxy [...] --exclude-inbound-ports 22`). I believe there should be short section in documentation about this, as it may be a little confusing for everyone not experienced with how our transparent-proxy works (so for most of the people).

**Comment by jakubdyszkiewicz** [comment]
It's documented now
