### ISSUE TITLE
Document `targetRef.kind: MeshGateway`

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma-website#1393]
### Description

Implemented when https://github.com/kumahq/kuma/issues/6956 is closed

**Comment by lahabana** [comment]
@michaelbeaumont what else is left ehre?

**Comment by michaelbeaumont** [comment]
Well not every resource supports it yet, so this would be closed after the issue in the description is done and documented. But we could also close it now, given that there's the "docs" checkbox in Kuma PRs

**Comment by lahabana** [comment]
@michaelbeaumont this was done right?
