### ISSUE TITLE
Request for more `skipCreatingInitialPolicies` documentation

### ISSUE THREAD

**Issue by cloudjumpercat** [kumahq/kuma-website#1428]
### Description

There’s a feature that came out in the previous Mesh version that a customer needs and couldn’t figure out how to use: `skipCreatingInitialPolicies`. It’s only documented here: https://kuma.io/docs/2.3.x/generated/resources/other_mesh/#mesh, and that doc didn't contain enough context about what that feature does. 

CRE would like a doc with an example. There's a KB that the support team created that you might be able to use:

> Question:
> 
> When deploying Kuma we would like to prevent the default policies from being created for a specific Mesh, how can this be achieved? 
> 
> Answer:
> 
> This feature became available starting in Kuma 2.3. To prevent the policies from being created you will need to modify your Mesh with the field skipCreatingInitialPolicies.
> 
> For example:
> 
> apiVersion: [kuma.io/v1alpha1](http://kuma.io/v1alpha1)
> kind: Mesh
> metadata:
>  name: gruber
> spec:
>  mtls:
>  enabledBackend: ca-1
>  backends:
>  - name: ca-1
>  type: builtin
>  dpCert:
>  rotation:
>  expiration: 1d
>  conf:
>  caCert:
>  RSAbits: 2048
>  expiration: 10y
>  routing:
>  zoneEgress: true
>  skipCreatingInitialPolicies:
>  - TrafficPermission
>  - TrafficRoute
> 
> This takes a list of policies, TrafficPermission, MeshRetry, etc or an ‘*’ can be used to skip all policies.

**Comment by lahabana** [comment]
I've added extra info in: https://github.com/kumahq/kuma-website/pull/1629
