### ISSUE TITLE
Kuma in production on universal docs should emphasise using postgres db

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma-website#1548]
### What happened?

Currently, in the section https://kuma.io/docs/2.5.x/production/cp-deployment/stand-alone/ we don't have any information about database requirements. We should add a note that in production its recommended.

**Comment by dascole** [comment]
@lukidzi 

I missed this issue, but do these satisfy the requirement? 

https://github.com/kumahq/kuma-website/pull/1593
https://github.com/kumahq/kuma-website/pull/1594

**Comment by lukidzi** [comment]
Yes, thank you for the contribution :)
