### ISSUE TITLE
Update `MeshFaultInjection` docs for `MeshGateway`

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma-website#1549]
### Description

We only support `to` with `spec.kind: MeshGateway`

**Comment by slonka** [comment]
seems like it's done 🤔 
![image](https://github.com/user-attachments/assets/6ff1f605-fda2-4fad-b23b-ad3219ac340e)

https://kuma.io/docs/2.8.x/policies/meshfaultinjection/#meshfaultinjection

@michaelbeaumont can you confirm?

**Comment by michaelbeaumont** [comment]
Yeah seems done, `to` is only under gateway
