### ISSUE TITLE
there's 2 assets directory which one should be removed

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-website#1597]
### What happened?

There's: https://github.com/kumahq/kuma-website/tree/master/app/_assets and https://github.com/kumahq/kuma-website/tree/master/app/assets .

When working on https://github.com/kumahq/kuma-website/pull/1595 `/app/assets` was the right one but is this always the case?

**Comment by fabianrbz** [comment]
`app/_assets` is meant for assets handled via `vite.js` (concatenation, compression, etc., so styles and javascript)
`app/assets` acts as a public folder, so everything else goes here.

Looks like images are duplicated, we can remove `app/_assets/images`.
