### ISSUE TITLE
Update the docs to use new policies in place of the legacy ones

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma-website#1599]
### Description

In all places where the docs were using legacy policies to suggest some behavior or to show examples we should replace it with the new policies instead.

* [x] https://github.com/kumahq/kuma-website/pull/1607
* [x] https://github.com/kumahq/kuma-website/pull/1608
* [ ] https://github.com/kumahq/kuma-website/pull/1613
* [x] Update [Networking / Non-mesh traffic](https://kuma.io/docs/dev/networking/non-mesh-traffic/) page with new policies - @slonka https://github.com/kumahq/kuma-website/pull/1615
  * Use `MeshProxyPatch` instead of `ProxyTemplate`
* [ ] @michaelbeaumont Update/Replace [Explore / Gateway](https://kuma.io/docs/dev/explore/gateway/) page with new policies
  * WIP https://github.com/kumahq/kuma-website/pull/1582
* [x] https://github.com/kumahq/kuma-website/pull/1614
* [X] @slonka - https://github.com/kumahq/kuma-website/pull/1618 - Update [Kuma in Production / Create multiple service meshes in a cluster](https://kuma.io/docs/dev/production/mesh/) page with new policies
  * Link to new policies
  * Replace `TrafficRoute` from the example with new policies

**Comment by slonka** [comment]
I'll take 

```
Update [Networking / Non-mesh traffic](https://kuma.io/docs/dev/networking/non-mesh-traffic/) page with new policies
Use MeshProxyPatch instead of ProxyTemplate
```
