### ISSUE TITLE
Update MeshLoadBalancingStrategy docs to reflect actual k8s topology tags

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma-website#1653]
### Description

We use the example of `k8s.io/az` etc in the docs for awareness, but should use the `topology.kubernetes.io/zone` standard labels for clarity probably?

ref: https://docs.konghq.com/mesh/latest/policies/meshloadbalancingstrategy/#disable-cross-zone-traffic-and-prioritize-traffic-the-dataplanes-on-the-same-node-and-availability-zone

**Comment by jakubdyszkiewicz** [comment]
Depends on https://github.com/kumahq/kuma/issues/9242

**Comment by lukidzi** [comment]
@slonka I think it was fixed
