### ISSUE TITLE
`installer.sh` should only consider commits that are first ancestors of the current `master`

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma-website#1668]
### Description

In the presence of merge commits, `installer.sh` will sometimes choose a commit from a PR branch that has been merged into `master` as the current `preview` version because:
* it's in the history returned by the GraphQL API
* it has a "green" status.

It should only consider commits that are first ancestors of the current `master` commit.

**Comment by lahabana** [comment]
IIUC this https://github.com/kumahq/kuma-website/pull/1710 fixes this issue.

**Comment by michaelbeaumont** [comment]
Yeah presumably `gh run list` doesn't return runs for commits on PR branches
