### ISSUE TITLE
Create `if_kuma` block

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma-website#1696]
### Description

Do we / should we have `if_kuma` block in docs? I was looking at zone auth docs https://docs.konghq.com/mesh/2.3.x/production/secure-deployment/certificates/#authentication-2 and this looks a bit weird, we should be pointing to https://docs.konghq.com/mesh/2.3.x/features/kds-auth/ right?

**Comment by lahabana** [comment]
Can we just do:

`{% if site.mesh_product_name == "Kuma" %}`

Like:

https://github.com/kumahq/kuma-website/blob/ef3725d7586a717b1d87933c68ebe83bd80bac1a/app/_src/quickstart/kubernetes-demo.md?plain=1#L193-L195
