### ISSUE TITLE
Clarify CNI installation section

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma-website#1753]
### What happened?

It's not clear how to install kuma-cni on gke with Cilium and also a bit confusing. It's easy to make a mistake while installing kuma-cni with Cilium on GKE and use a Cilium instruction which doesn't work

To chain on GKE kuma-cni with Cilium I had to set `cni.confName=10-gke-ptp.conflist` and the same binary paths as for GKE

**Comment by Icarus9913** [comment]
We should add tips with the current `Cilium` and `Calico` to explain that it belongs to the standard k8s cluster(like kubeadm). And if you would like to install `Kuma-CNI` with `Cilium/Calico` on GKE you to switch to the `Google-GKE` section.
