### ISSUE TITLE
Doc bold font issue

### ISSUE THREAD

**Issue by Icarus9913** [kumahq/kuma-website#1764]
### What happened?

https://kuma.io/docs/2.7.x/introduction/overview-of-kuma/

![WeChat0bd4c0c0b26cfa3ceab2db9cb2456f39](https://github.com/kumahq/kuma-website/assets/42732678/7a9cd349-27cf-4730-849e-5274a8183319)

**Comment by Icarus9913** [comment]
For the first issue line, I think we fix it with 
```text
* {% if_version gte:2.6.x %}**Single-zone{% endif_version %}{% if_version lte:2.5.x %}**Standalone{% endif_version %} and multi-zone**: Supports multiple clouds, regions, and Kubernetes clusters with native DNS service discovery and ingress capability.
```

But for the latter sub-list gramma, I tried the upper way but not works. 
@johncowen Do you have any ideas?

<img width="880" alt="image" src="https://github.com/kumahq/kuma-website/assets/42732678/ad640435-d2be-43bb-93e1-0591e2203458">

**Comment by johncowen** [comment]
Hmm yeah weird, its this fiddly `if_version` thing again 🤔 

I had a mess around with different approaches to listing/linebreaks and things, but couldn't get it to so what we want.

I wonder if just making completely separate lists for the different versions would be better? There would be some duplication but at least we might be able to get it to render how we want?

**Comment by johncowen** [comment]
If it was me I'd just do it here for now (if that solves the issue here)

I remember seeing a PR somewhere for improving how `if_version` works, not sure if thats applied here yet or will come soon, so it might be less fiddly to use pretty soon.

**Comment by Icarus9913** [comment]
@johncowen Hey jc, I just forgot. 
This page is only one. It's an [overview](https://github.com/kumahq/kuma-website/blob/master/app/_src/introduction/overview-of-kuma.md) page to summary the whole versions.

I mean, it seems like we can not do separate lists for different versions because all different versions share the common one page.

**Comment by johncowen** [comment]
I 'think' (but not totally sure 😅 ) that something like the following would do it. There's plenty of repetition but it works fine 🤷‍♂️ .

(just to note I'm not totally sure that the below versioning is correct, but if not we just need to make more variations
 of full lists)

What do you think?


```md
{% if_version lte:2.5.x %}
* **Universal and Kubernetes-native**: Platform-agnostic, can run and operate anywhere.
* **Standalone and multi-zone**: Supports multiple clouds, regions, and Kubernetes clusters with native DNS service discovery and ingress capability.
  * [Read more about standalone deployments](/docs/{{ page.version }}/production/deployment/stand-alone/)
  * [Read more about multi-zone deployments](/docs/{{ page.version }}/production/deployment/multi-zone/)
* **Multi-mesh**: Supports multiple individual meshes with one control plane, lowering the operational costs of supporting the entire organization.
* **Attribute-based policies**: Lets you apply fine grained service and traffic policies with any arbitrary tag selector for `sources` and `destinations`.
* **Envoy-based**: Powered by Envoy sidecar proxies, without exposing the complexity of Envoy itself.
* **Horizontally scalable**
* **Enterprise-ready**: Supports mission critical enterprise use cases that require uptime and stability.
{% endif_version %}

{% if_version gte:2.6.x %}
* **Universal and Kubernetes-native**: Platform-agnostic, can run and operate anywhere.
* **Single-zone and multi-zone**: Supports multiple clouds, regions, and Kubernetes clusters with native DNS service discovery and ingress capability.
  * [Read more about single-zone deployments](/docs/{{ page.version }}/production/deployment/single-zone/)
  * [Read more about multi-zone deployments](/docs/{{ page.version }}/deployments/multi-zone)
* **Multi-mesh**: Supports multiple individual meshes with one control plane, lowering the operational costs of supporting the entire organization.
* **Attribute-based policies**: Lets you apply fine grained service and traffic policies with any arbitrary tag selector for `sources` and `destinations`.
* **Envoy-based**: Powered by Envoy sidecar proxies, without exposing the complexity of Envoy itself.
* **Horizontally scalable**
* **Enterprise-ready**: Supports mission critical enterprise use cases that require uptime and stability.
{% endif_version %}


```

**Comment by Icarus9913** [comment]
Agree, this is a good idea and we can do this.👍🏻
