### ISSUE TITLE
No hyperlink generated

### ISSUE THREAD

**Issue by Icarus9913** [kumahq/kuma-website#1766]
### What happened?

https://kuma.io/docs/2.7.x/networking/service-discovery/#service-discovery

![WeChat2d0da3cb6d75fc7045b0bd87c0c2b7d9](https://github.com/kumahq/kuma-website/assets/42732678/214ecc65-cc06-4c6c-8db2-4eb4f329fe50)

**Comment by Icarus9913** [comment]
I gonna take a look

**Comment by Icarus9913** [comment]
OK, there are some directories missing. We don't have `2.1.x`, `2.2.x` ... `2.7.x` folders, but only `2.0.x`.
And for the previous `1.2.x`, `1.3.x` and some else all good.

https://github.com/kumahq/kuma-website/tree/master/app/docs

<img width="139" alt="image" src="https://github.com/kumahq/kuma-website/assets/42732678/055c39f0-8bca-42cf-94dc-77ae2d5636a6">

**Comment by Icarus9913** [comment]
```text
{% if_version lte:1.9.x %}
* On Kubernetes by looking at the address of the `Pod`.
* On Universal by looking at the inbound listeners that have been configured in the [`inbound` property](/docs/{{ page.version }}/documentation/dps-and-data-model/#dataplane-specification) of the data-plane specification.
{% endif_version %}
{% if_version gte:2.0.x %}
* On Kubernetes by looking at the address of the `Pod`.
* On Universal by looking at the inbound listeners that have been configured in the [`inbound` property](/docs/2.0.x/generated/resources/proxy_dataplane) of the data-plane specification.
{% endif_version %}
```

I use a hardcode `2.0.x` in the second list. But it might make the users confused that once in a `2.7.x` page would jump to `2.0.x`.

I don't know whether we should supplement the other version docs folds. (Since I'm not aware of the differences between the 2.x.x versions, I'm afraid of making mistakes here.)

**Comment by lahabana** [comment]
This file is there: https://github.com/kumahq/kuma-website/blob/master/app/_src/production/dp-config/dpp-on-universal.md
