### ISSUE TITLE
The description of Envoy requirement is confusing.

### ISSUE THREAD

**Issue by spacewander** [kumahq/kuma-website#1776]
### What happened?

In https://kuma.io/docs/2.7.x/introduction/kuma-requirements/#envoy,

> Versions of envoy supported are: ~1.25.0 which means >=1.25.0 and <1.25.0.
> You can find the current version in the [version.sh](https://github.com/kumahq/kuma/blob/master/tools/releases/version.sh#L11) file.

For the first sentence, if the supported Envoy is both >=1.25.0 and <1.25.0, it means we support every version of Envoy. Maybe this sentence misses a patch version?

And what's the difference between the supported version and the currently used version? I find that the current used version is 1.29.4, which is much newer than the supported one.

**Comment by jakubdyszkiewicz** [comment]
> Triage: It is a bug in docs. We support Envoy version specified here https://github.com/kumahq/kuma/blob/master/tools/releases/version.sh#L11. We support -2 minor version of Kuma https://kuma.io/docs/2.7.x/production/upgrades-tuning/upgrades/#upgrade-kuma so the range starts from envoy version in -2 minor release of Kuma
