### ISSUE TITLE
Namespace <-> Mesh relation on K8S

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma-website#178]
We should make clear to the users that `mesh` is a higher-level concept than `namespace`. Meaning - you can have one mesh across multiple namespaces.
Also add a note that when Kuma applies policies, it fetches them from all the namespaces.

**Comment by lahabana** [comment]
@jakubdyszkiewicz is this something you can add when you'll add docs on mesh constraints as they seem quite close?
