### ISSUE TITLE
Update docs for disabling IPv6

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma-website#1834]
### What happened?

https://github.com/kumahq/kuma/pull/8939 introduce ip family mode. Users now need to use this setting to disable IPv6.

**Comment by jijiechen** [comment]
With the introduction of  configuration item `runtime.kubernetes.injector.sidecarContainer.ipFamilyMode`  and the corresponding annotation "kuma.io/transparent-proxying-ip-family-mode" on Pod, we now have a new way to disable ipv6.  So we need to update the doc to clarify this.

Update doc for 2.7 onwards at: https://kuma.io/docs/2.7.x/production/dp-config/ipv6/#disabling-ipv6

The default mode of Kuma is assuming dual stack support on the cluster and sometimes this is not true. 
It unfortunate that by default things won't work on EKS.
