### ISSUE TITLE
Add Vale rules for capitalization

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma-website#1837]
### Description

We have a lot of unnecessary capitalization in our docs, see [this example](https://github.com/kumahq/kuma-website/pull/1835/files#diff-51dc21040d495126495ff0b37efca38592925f2f284a5d81663ae8b61ba9bbedL7). Let's check if Vale can help.

**Comment by lahabana** [comment]
@michaelbeaumont this is getting fixed now that vale is back in play no?

**Comment by michaelbeaumont** [comment]
Yeah, it's still a case by case process. Maybe Vale can do disallow by default or something. I'll look into this.

**Comment by michaelbeaumont** [comment]
Added error level for headings at least: https://github.com/kumahq/kuma-website/pull/1992
