### ISSUE TITLE
Egress origin missing from MeshProxyPatch docs

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma-website#1840]
### What happened?

It's here: https://github.com/kumahq/kuma/blob/dca7f04e9e075ae154ad4f87c4ec2ee1c9ae2dc5/pkg/plugins/policies/meshproxypatch/api/v1alpha1/schema.yaml#L84

but it's not here:
https://kuma.io/docs/dev/reference/proxy-template/#origin

**Comment by michaelbeaumont** [comment]
We should only add this to the docs when it works, at the moment it's not possible to apply a patch to egress
