### ISSUE TITLE
Issue with port config on zone-ingress page

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-website#1861]
### What happened?

https://kuma.io/docs/2.8.x/production/cp-deployment/zone-ingress/#zone-ingress

The port config in the `[Universal]` tab `10000` and `10001` are problematic.

![Screenshot 2024-07-26 at 12 39 53](https://github.com/user-attachments/assets/2f3af9b6-785b-44c1-b118-bfcf89df7724)

In quick setups like demos we usually don't add a LB in front of the ingress and just run a single zoneIngress. Even when using a LB it would be weird to use a different port

**Comment by bartsmykla** [comment]
> triage: it's the example in the docs we should change
