### ISSUE TITLE
Update policy and targetRef docs to reflect using real resources instead of `kuma.io/service` tags

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma-website#1892]
### Description

In particular: https://kuma.io/docs/2.8.x/policies/targetref

**Comment by slonka** [comment]
Chatted with Mike about https://kuma.io/docs/2.8.x/policies/targetref - some highlights:
- needs to be rewritten entirely tbh
- remove the top level MeshService
- talk about real MeshServices with `sectionname` and `port` for backends
- not well structured
  - try writing a better intro
  - try adding some mermaid graphs to illustrate what selects what
  - check if we're missing examples
  **- should this also contain the updates with regards to policies on namespace?** (WDYT @lobkovilya - do we have an issue for that?)

<a href="#user-content-1" id="1">#</a> WDYT about the other pages? Should we just switch to "new" `MeshService` or show examples for both with the "old" (`kuma.io/service` style) having some sort of deprecation notice?

**Comment by lobkovilya** [comment]
Policies on namespace should be covered by this issue https://github.com/kumahq/kuma-website/issues/1824

**Comment by michaelbeaumont** [comment]
Gonna close this since we have #1919 and a rewrite in https://github.com/kumahq/kuma-website/pull/1956

**Comment by lobkovilya** [comment]
@michaelbeaumont AFAIK #1919 doesn't cover:
> * remove the top level MeshService

Also I started looking at `backendRefs` rewrite, but I can probably have a separate issue for that

**Comment by michaelbeaumont** [comment]
@lobkovilya opened https://github.com/kumahq/kuma-website/issues/1995

**Comment by lobkovilya** [comment]
I closed https://github.com/kumahq/kuma-website/issues/1962 just few hours ago because we discussed with @slonka that it's covered by this issue 😄

**Comment by michaelbeaumont** [comment]
OK that's already opened so :shrug:
