### ISSUE TITLE
Document how tags are converted for Dataplanes on K8S

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma-website#191]
* we copy all labels from Pod
* we add service tag based on the matched Service object
* we add protocol tag based on `service.kuma.io/protocol` annotation

**Comment by lahabana** [comment]
@jakubdyszkiewicz this is covered by: #623 isn't it?

**Comment by michaelbeaumont** [comment]
@lahabana Definitely seems covered by that, closing this.
