### ISSUE TITLE
"Install kumactl" page should be easier to find

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma-website#1921]
### What happened?

At this moment the page that aggregates all the installation info https://kuma.io/install/2.8.x/ apparently doesn't have link to https://kuma.io/docs/2.8.x/production/install-kumactl/#install-kumactl

**Comment by slonka** [comment]
>Triage: the proper fix is to have a page like we used to:

![image](https://github.com/user-attachments/assets/00f552b1-b4db-4805-9a58-235e8927edc9)

> but without the repetition (kumactl on macos installs the same as on debian)
> and to have this page be linked on every guide that requires `kumactl` as a prerequisite
