### ISSUE TITLE
The Gateway API guide incorrect install kuma CRs 

### ISSUE THREAD

**Issue by csantanapr** [kumahq/kuma-website#1924]
### What happened?

In the API Gateway Guide 
Tells the user to install demo with this command
```
kumactl install demo | kubectl apply -f -
```
The problem is that this command install extra resources like MeshGateway, MeshGatewayInstance, and MeshHTTPRoute.

The main target of the guide is for the user to create the CRs using API Gateway CRDs not Kuma.

**Comment by michaelbeaumont** [comment]
Yeah, the command should probably include `--without-gateway`
