### ISSUE TITLE
Update new policies example to use MeshSubset

### ISSUE THREAD

**Issue by schogges** [kumahq/kuma-website#1962]
### What happened?

We still have `MeshService` in top `targetRef` in our examples. These should be updated to `MeshSubset`.

**Comment by lahabana** [comment]
We should go over the docs before announcing 2.9

**Comment by lobkovilya** [comment]
It's already covered in https://github.com/kumahq/kuma-website/issues/1892#issuecomment-2371149455:
> * remove the top level MeshService

So it's a dup of #1892

**Comment by slonka** [comment]
We decided to close https://github.com/kumahq/kuma-website/issues/1892 so I'm reopening this because that scope is not yet addressed.

**Comment by slonka** [comment]
done via https://github.com/kumahq/kuma-website/pull/2003
