### ISSUE TITLE
Deploy Kuma on Universal is broken

### ISSUE THREAD

**Issue by wahmedswl** [kumahq/kuma-website#1997]
### What happened?

Hi!

Quick Start example for Deploy Kuma on Universal is broken. Able to bring-up Redis service via kuma-dp but not the 2nd app because it wanna run admin on 9902 but it's already taken by redis service ```"dataplane.readinessReporter.port": "9902",```. How to configure the  ```"dataplane.readinessReporter.port"``` explicitly via dataplane cli.

Thanks

**Comment by jijiechen** [comment]
These port unfortunately can't be configured via dataplane manifest. 
Regarding you questions of "configuring multiple services again single Dataplane", I don't get your actual idea. It's recommended to run only a single dataplane on a host.

**Comment by wahmedswl** [comment]
@jijiechen Yes, that's why asked how to run multiple services on same dataplane? E.g. they create separate dataplane for every service; just look at the example in quick start, Redis and Example app have separate dataplane.

**Comment by jijiechen** [comment]
Conceptually a dataplane is a running instance of a service, so the relation `service:dataplane` has a `1:N` mapping. In a typical microservices architecture, services are isolated units serving different business functionalities; and dataplanes are instances of each of these services.
On the other hand, technically, we generate different service objects/resources when a dataplane defines multiple ports in its manifests.

**Comment by vovasoft** [comment]
export KUMA_READINESS_PORT=9903
export KUMA_APPLICATION_PROBE_PROXY_PORT=0
kuma-dp run

It's not work

**Comment by Automaat** [comment]
@vovasoft you need to put specific port in `export KUMA_APPLICATION_PROBE_PROXY_PORT` for it to work

**Comment by Automaat** [comment]
The quickstart demo now works after rewritting it, and errors from this issues are now solved by: https://github.com/kumahq/kuma-website/pull/2005

**Comment by jijiechen** [comment]
Hi @vovasoft  we'll continue discussing in this issue https://github.com/kumahq/kuma-website/issues/2010
