### ISSUE TITLE
It doesn't work totally, let me create the issue in Chinese directly to be productively

### ISSUE THREAD

**Issue by vovasoft** [kumahq/kuma-website#2010]
### What happened?

第一个问题，创建token文件需要增加日期参数：--valid-for=24h，否则会报错，建议修改一下ReadMe

第二个问题，在一个机器上，第二次启动kuma-dp run的时候，会提示9902端口被占用，这个问题我之前提过，有个老师说用

export增加环境变量，我试了，好像不行，依然会报错。我建议开发者自己试一下。
export KUMA_READINESS_PORT=9903
export KUMA_APPLICATION_PROBE_PROXY_PORT=0
kuma-dp run
上面的环境变量并不管用

新手教程很重要，尤其是非k8s环境，大部分人没有条件搭建k8s环境，其实用docker也行，但你们并没有docker教程。

第三个问题，我今天尝试用不同服务器运行kuma和其他服务，最新版的二进制文件，对gclib的版本要求很高，需要有2.28，2.29，并不方便，这非常不利于kuma的使用和宣传，你们知道升级C++相关的东西有多麻烦吗？

第四个问题，权限很复杂，在多服务器运行的时候提示cert.pem文件配置，例如你们会提示：kumactl generate tls-certificate --type=server --cp-hostname=，但这个脚本根本就无法运行，因为没有--cp-hostname这个参数，只有--hostname，建议你们更新一下。而且，即便是生成了pem文件，这个文件只支持内网IP，例如阿里云，外网地址依然无法访问。而且而且，即便在内网运行，依然会有各种错误。

已经3天了，我根本无法运行一个简单的Demo，相比其他service mesh框架，例如consul，20分钟就能完成demo的创建，而kuma用了3天无法完成1个简单的测试。

**Comment by Automaat** [comment]
hello @vovasoft we know that our quickstart was in a bad state, and we have rewritten it yesterday. I hope that issues with universal quickstart demo should be now solved

**Comment by jijiechen** [comment]
Here is a translation to the original Chinese comment:

> ### First issue: missing parameter in example command line

> When creating a token file, you need to add the date parameter: `--valid-for=24h`, otherwise an error will be reported. It is recommended to modify the ReadMe.

> ### Second issue: port conflicts when running two instances of Kuma on the same machine

> When starting `kuma-dp run` for the second time, it will fail that port `9902` is already in use. I've reported this issue before in issue https://github.com/kumahq/kuma/issues/11824. Someone in the project suggested using `export` to add environment variables. I tried it, but it seems not to work: it still reports the error. I suggest you developers should try it by yourselves.

```sh
export KUMA_READINESS_PORT=9903
export KUMA_APPLICATION_PROBE_PROXY_PORT=0
kuma-dp run
```

> The above environment variables do not work.

> Tutorials for beginners are important, especially for non-k8s environments. It's not easy for most people to create a k8s environment. We can also accept using docker as an alternative, however, you do not provide the tutorial works based on Docker.

> ### Third issue: high version requirement of the glibc

> When I was trying to run kuma and other services on different servers today. The latest version binaries requires a high version of glibc (requires 2.28 and 2.29). 
 
> This is not convenient, it must be a drawback of using and promoting Kuma. I hope you know how troublesome it is to upgrade C++ related things.

> ## Fourth issue: very complicated certificate configuration

> When running on multiple servers, you suggested I should configure the `cert.pem` file. For example, you suggested running `kumactl generate tls-certificate --type=server --cp-hostname=`. However, this script does not work at all, because there is no such parameter `--cp-hostname` and it should be `--hostname`. So you should just update your docs.

> Moreover, after the pem file is generated, this file only supports internal IP ranges. When I work on a cloud env like Alibaba Cloud, I can't use it using a public network address. Even I run it using an internal network, there are still various errors.

> It has been 3 days, and I can't run a simple demo at all. Compared to other service mesh frameworks, such as Consul, it can complete the demo creation in 20 minutes, while Kuma took 3 days on a simple trial.

**Comment by Automaat** [comment]
@vovasoft question about fourth issue, where did you find `kumactl generate tls-certificate --type=server --cp-hostname=` this command? I only found references of using `--cp-hostname` in kuma version 1.2 and 1.3 which are unsupported for more than year, last supported version of Kuma is 2.5.x

**Comment by vovasoft** [comment]
For instance, if you start kuma-cp run on Server A and execute kuma-dp run on Server B with the --cp-address configured to Server A's IP address, an error will occur. The version I'm using is 2.8.4. The error message will prompt something related to --cp-hostname. This information is printed in the log. When I copy it out for use, it results in an error. Hahaha.

**Comment by Icarus9913** [comment]
Hey @vovasoft 

It seems like that you're trying to use kuma in universal mode right? Could you please paste the doc link that you followed? Maybe we can improve it.

1. I just verified the [quickstart-universal](https://kuma.io/docs/2.9.x/quickstart/universal-demo/) for the latest `2.9.x` and `2.8.x`, `2.7.x`. The doc command requires us to specify the argument `--valid-for=720h`

```text
kumactl generate dataplane-token --tag kuma.io/service=redis --valid-for=720h > /tmp/kuma-token-redis
kumactl generate dataplane-token --tag kuma.io/service=demo-app --valid-for=720h > /tmp/kuma-token-demo-app
```

So, could you please paste the doc link you read and let's improve it.

2. Just open 2 Terminals, run the following command in the first one:

```text
KUMA_READINESS_PORT=9901 KUMA_APPLICATION_PROBE_PROXY_PORT=9902  kuma-dp run ......
```

run the following command in the second one:

```text
KUMA_READINESS_PORT=9904 KUMA_APPLICATION_PROBE_PROXY_PORT=9905 kuma-dp run ......
```

**Comment by jijiechen** [comment]
@vovasoft  It's nice to see you here. Could you add me on WeChat, so we can talk directly in Chinese?
My account is `jijiechen90`.

I'll remove this message 60 mins later.

**Comment by Automaat** [comment]
As for the glibc requirements, official Envoy binary started requiring glibc 2.30 two years ago: https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.24/v1.24.0.html#incompatible-behavior-changes I think that if someone needs older version they either need to upgrade glibc or build Envoy and Kuma with older glibc

**Comment by Automaat** [comment]
> For instance, if you start kuma-cp run on Server A and execute kuma-dp run on Server B with the --cp-address configured to Server A's IP address, an error will occur. The version I'm using is 2.8.4. The error message will prompt something related to --cp-hostname. This information is printed in the log. When I copy it out for use, it results in an error. Hahaha.

@vovasoft ok, I see now, this issue was fixed: https://github.com/kumahq/kuma/pull/11318 and fix is released in 2.9.0

**Comment by jijiechen** [comment]
Regarding the glibc version dependency, we do have a workaround to run Envoy on an OS shipped with old versions of glibc, it's a little tricky though.

Here are detailed instructions:
https://github.com/kumahq/envoy-builds?tab=readme-ov-file#bundling-with-a-custom-glibc

**Comment by jakubdyszkiewicz** [comment]
> Triage: Can you try the new quickstart https://kuma.io/docs/2.9.x/quickstart/universal-demo/
