### ISSUE TITLE
Broken some image links on the v0.5.0 docs

### ISSUE THREAD

**Issue by ryysud** [kumahq/kuma-website#202]
There are image differences between [v0.4.0](https://github.com/Kong/kuma-website/tree/master/docs/.vuepress/public/images/docs/0.4.0) and [v0.5.0](https://github.com/Kong/kuma-website/tree/master/docs/.vuepress/public/images/docs/0.5.0).

So some image links are broken in v0.5.0 docs as below:
https://github.com/Kong/kuma-website/search?q=diagram-02.jpg+OR+diagram-03.jpg+OR+diagram-06.jpg+OR+diagram-07.jpg+OR+diagram-10.jpg+OR+diagram-11.jpg+path%3A%2Fdocs%2Fdocs%2F0.5.0&unscoped_q=diagram-02.jpg+OR+diagram-03.jpg+OR+diagram-06.jpg+OR+diagram-07.jpg+OR+diagram-10.jpg+OR+diagram-11.jpg+path%3A%2Fdocs%2Fdocs%2F0.5.0

It would be good to fix this for kuma users.

**Comment by subnetmarco** [comment]
@bloqhead

**Comment by subnetmarco** [comment]
@bloqhead updates?

**Comment by Bradamant3** [comment]
Closing because these are such old versions. Feel free to reopen with a PR to fix if older versions are still in use, and thanks!
