### ISSUE TITLE
In the kuma installation document, the version jump is abnormal.

### ISSUE THREAD

**Issue by ty-dc** [kumahq/kuma-website#2090]
### What happened?

1. Go to https://kuma.io/install/latest/
2. Install the latest version, but it shows 1.2.x
   
![image](https://github.com/user-attachments/assets/59bb2da6-5085-4a8b-9fdd-b7c7e4e86b58)

3. Tried to switch to another version, but was still redirected to version 1.2.x.
![2024-11-18 15 05 16](https://github.com/user-attachments/assets/430c88e1-47e4-4bbd-9b33-748387798749)

**Comment by lobkovilya** [comment]
> Triage: on the main page "Get Started / OSS" leads to https://kuma.io/install/latest/. We probably should fix this link to go to https://kuma.io/docs/latest/introduction/install-kuma/ (same as green "Install" button)

**Comment by jijiechen** [comment]
We have several places leading to "https://kuma.io/install/latest/":

1. On the [Kuma repo page](https://github.com/kumahq/kuma), at the right hand side, in the description section, there is the link
2. On the README of the Kuma repo, at [section "Get Started"](https://github.com/kumahq/kuma?tab=readme-ov-file#get-started), there is the link.
3. From the Kuma GUI, a button shows up when there is a newer version available, this button links to this page as well.

<img width="301" alt="image" src="https://github.com/user-attachments/assets/cfc6134c-e5bb-412b-b54a-87d1aaf2d61e">

**Comment by lahabana** [comment]
Thanks for reporting! I've opened a PR to fix this
