### ISSUE TITLE
Automatically deploy a preview of Kong docs on PRs

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma-website#2093]
### Description

We sometimes miss things not working because we only check kuma-website. E.g.:

https://kuma.io/docs/2.9.x/quickstart/universal-demo/ 

![image](https://github.com/user-attachments/assets/394f4a12-5ecb-44f7-96a9-de8a61c3460a)

https://docs.konghq.com/mesh/latest/quickstart/universal-demo/

![image](https://github.com/user-attachments/assets/790968c6-19bf-439e-ba79-eecaeeac1200)

**Comment by lukidzi** [comment]
> triage: seems like a good idea, but I double people are frequently checking both previous.
