### ISSUE TITLE
Missing docs for `MeshRetry` and `MeshHTTPRoute`

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma-website#2112]
### What happened?

There is [an e2e test](https://github.com/kumahq/kuma/blob/fa008d1587e110d7dae97f9e1dca450e552be4b5/test/e2e_env/universal/meshretry/http.go#L250) but no docs

**Comment by lukidzi** [comment]
duplicate of https://github.com/kumahq/kuma-website/issues/2110
