### ISSUE TITLE
Add clarity to Kubernetes docs

### ISSUE THREAD

**Issue by devadvocado** [kumahq/kuma-website#31]
Right now, step four in the kubernetes docs is:
```sh
kumactl config control-planes add --name=XYZ --address=http://address.to.kuma:5681
```
without any additional information.

Need to add following:
1. `kubectl port-forward ..` or `kubectl proxy` to make the `kuma-control-plane` available to kumactl on the host
2. the use the cluster ip of `kube-control-plane` as the address.to.kuma

**Comment by Bradamant3** [comment]
Looks as though this issue has been addressed and then mooted by larger-scale docs rework. Thanks!
