### ISSUE TITLE
A better best practices about Kuma on Universal

### ISSUE THREAD

**Issue by nickolaev** [kumahq/kuma-website#312]
From discussions in the community, the interest to running Kuma in Universal or Hybrid mode is very big. We lack best practices examples of: systemd, Docker, Docker Compose. With the advancements in Kuma, we now have various deployment scenarios which we may need to go through in a systematic and practical manner.

**Comment by lahabana** [comment]
This is a little too generic. Closing this and we should open smaller, focused issues.
