### ISSUE TITLE
Add recommended replication factor for kuma-cp deployment on Kubernetes

### ISSUE THREAD

**Issue by xenji** [kumahq/kuma-website#397]
The default deployment, generated by kumactl, comes with a replicaCount of 1 for kuma-cp. Although the documentation mentions, that the kuma-cp is horizontally scalable, the documentation lacks the information about a recommended setting for production use. 

In the Community Slack, we had a discussion about this topic and it turned out that a quorum-able count (reads: 2/3, 3/5, 4/7, etc) seems to be the recommended option. Reference: https://kuma-mesh.slack.com/archives/CN2GN4HE1/p1615466512113300

Recommendations of this kind help people like me to get a good start with kuma ;)

**Comment by lahabana** [comment]
Probably should go in the "production" docs as this is valuable info. The answer is 2 (except if perf requires you to have more than 2)

**Comment by lahabana** [comment]
This was mentionned there: https://kuma.io/docs/1.7.x/documentation/upgrades/#upgrades and this will be rementionned in #630 and #629
