### ISSUE TITLE
Document how to create an ingress Dataplane

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma-website#455]
In https://kuma.io/docs/1.1.6/documentation/dps-and-data-model/#ingress, creating an ingress dataplane is described like this

> The recommended way to deploy an Ingress dataplane in Kubernetes is to use kumactl, or the Helm charts as specified in multi-zone. It works as a separate deployment of a single-container pod.

What are the specific `kumactl` commands that I need to use to create an ingress Dataplane? It's not obvious from the `kumactl` help or from the source.

**Comment by nickolaev** [comment]
We are changing this, there is going to be a dedicated ZoneIngress resource. @lobkovilya

**Comment by jpeach** [comment]
> We are changing this, there is going to be a dedicated ZoneIngress resource. @lobkovilya

Is there a design doc or an issue with more detail?

**Comment by jpeach** [comment]
I think the other thing that's confusing me here is that in Kubernetes, I don't think there is an ingress DP, it's just using standard LoadBalancer services.

**Comment by nickolaev** [comment]
> I think the other thing that's confusing me here is that in Kubernetes, I don't think there is an ingress DP, it's just using standard LoadBalancer services.

There is  Zone Ingress in K8s too. It is just an instance of the kuma-dp container.

**Comment by lahabana** [comment]
Switched to zoneIngress
