### ISSUE TITLE
Document kuma-dp dataplane resource templating

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma-website#465]
The file that is passed to the `kuma-dp --dataplane-file` option is a [mustache](https://github.com/mustache/mustache) template that can be expanded with variables taken from the `--dataplane-var`.

It would be great if this was documented, possibly with examples about how it can be useful for different deploments, e.g. the use case in `examples/ecs/workload.yaml`.

**Comment by lahabana** [comment]
Duplicate of #269
