### ISSUE TITLE
Provide full examples of policies/objects

### ISSUE THREAD

**Issue by scottslowe** [kumahq/kuma-website#472]
Several of the documentation pages do not provide full examples of the policy/object specification. Since these specifications do not appear to be publicly documented elsewhere (barring someone manually reviewing the code), the Kuma documentation should be updated to include full examples of the specification for _all_ policies/objects.

As of 28 June, the following policies/objects did not appear to provide full examples (if the examples provided are full examples, it is not made clear to the reader/viewer):

* Mesh
* Traffic Permissions
* Traffic Metrics
* Traffic Trace
* Fault Injection
* Health Check
* Proxy Template (but I can understand why this one wouldn't)
* External Service
* Retry
* Timeout

In some cases (like Rate Limit), it appears that we document some of the fields outside of an example, which is fine for now. Ultimately, though, we should strive for consistency in how we document and present this information to Kuma users.

**Comment by Bradamant3** [comment]
We're planning to integrate https://github.com/kumahq/kuma/pull/1741 but have been waiting on Jekyll migration for kuma-website to avoid rework. The migration is looking good; I'll be working with @bartsmykla as soon as we get the next Kuma release out the door. lmk if you have ideas about how to present/lay out the information, or thoughts about content we'd add manually.

**Comment by scottslowe** [comment]
@Bradamant3 Awesome, thanks for the update.

WRT to content layout: given that the website needs to perform dual functions (serve as a reference for things like object specifications **and** provide instructions on how to perform tasks like configuring mTLS or enabling locality-aware load balancing) it seems reasonable to re-organize content into that sort of arrangement. The "tasks" versus "concepts" arrangement of the Kubernetes docs is a reasonable comparison, IMO.

**Comment by Bradamant3** [comment]
@scottslowe yep wrt K8s docs, although in this case refdocs are probably the better comparison (kubectl more than apiref)

**Comment by scottslowe** [comment]
This issue is still relevant. Users have _no_ way of knowing the full spec for any Kuma policies/objects, especially considering there is no `kubectl explain` support.

**Comment by slonka** [comment]
I think new policies have full examples. Should we backfill old policies as well. WDYT @johnharris85 ?

**Comment by johnharris85** [comment]
I don't think we need to.

**Comment by michaelbeaumont** [comment]
Let's close this then. There's always the generated spec for old policies, e.g. https://kuma.io/docs/2.2.x/generated/resources/policy_health-check/
