### ISSUE TITLE
Tracing configuration example YAML switched between Kubernetes and Universal

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma-website#496]
Something has gone wrong on the tracing example https://kuma.io/docs/1.2.3/policies/traffic-trace/#add-jaeger-backend. Note that the Universal tab contains both Kubernetes and Universal YAML blocks

![Screenshot from 2021-08-04 16-06-01](https://user-images.githubusercontent.com/9917/128130437-563a31ed-d16f-44ff-8eb8-4b2039396dc8.png)

**Comment by Bradamant3** [comment]
Thanks for catching, @jpeach -- I'll push a fix today (August 4 UTC-4 to be precise)
