### ISSUE TITLE
TrafficRoute example YAML contains mis-quoted YAML strings

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma-website#498]
Take the example YAML from https://kuma.io/docs/1.2.3/policies/traffic-route/#usage and apply it with `kumactl`:

```
jpeach@greenling:~/upstream/konghq/kuma$ kumactl apply -f /tmp/t
Error: YAML contains invalid resource: error converting YAML to JSON: yaml: line 30: found unknown escape character
jpeach@greenling:~/upstream/konghq/kuma$ kumactl apply -f /tmp/t
Error: YAML contains invalid resource: error converting YAML to JSON: yaml: line 35: found unknown escape character
```

The problem is escapes pattern substitutions like `"\2/instance/\1"`. Because of the double-quote, the YAML parser tries (and fails) to interpret this as an escape. This should be using single quotes.

**Comment by Bradamant3** [comment]
@jpeach thanks for catching this! Will fix up, but question before I do (because single/double quotes have caught me and others out so much with json as well as yaml ...) -- single quotes for everything, not just regex/substitutions?
