### ISSUE TITLE
Remove references to kuma.io/region and kuma.io/subzone

### ISSUE THREAD

**Issue by scottslowe** [kumahq/kuma-website#516]
The locality-aware load balancing implementation in all releases of Kuma so far doesn't actually use these tags, so they have no effect whatsoever. We should remove them from the documentation.

**Comment by Bradamant3** [comment]
Fixed with the release of the 1.3.0 docs (added small things to larger PR, sorry!) with many thanks for filing the follow-up issue too ❤️
