### ISSUE TITLE
Update locality-aware load balancing documentation

### ISSUE THREAD

**Issue by scottslowe** [kumahq/kuma-website#517]
This issue is pending resolution of this issue: https://github.com/kumahq/kuma/issues/2689

Once this issue is resolved and "proper" locality-aware load balancing functionality has been implemented, we need to update the documentation for locality-aware load balancing.

**Comment by Bradamant3** [comment]
Let's keep for tracking purposes, since the linked issue is also still open (again for tracking/investigation purposes).

**Comment by scottslowe** [comment]
Although the linked issue has been resolved, our documentation still does not (AFAIK) explain the basics behind locality-aware load balancing. I think this issue should be kept open.

**Comment by michaelbeaumont** [comment]
Merged https://github.com/kumahq/kuma-website/pull/694.
Closing for now because we'll update the docs when we close https://github.com/kumahq/kuma/issues/2689
