### ISSUE TITLE
Wrong docker pull and run commands mentioned in documentation.

### ISSUE THREAD

**Issue by jaikratsinghtariyal** [kumahq/kuma-website#534]
**Documentation**
https://kuma.io/docs/1.3.0/installation/docker/

there are no tag or version given for images in 

1.     kuma-cp: at docker.io/kumahq/kuma-cp:
2.     kuma-dp: at docker.io/kumahq/kuma-dp:
3.     kumactl: at docker.io/kumahq/kumactl:
4.     kuma-prometheus-sd: at docker.io/kumahq/kuma-prometheus-sd:

I used below docker pull commands

1. docker pull kumahq/kuma-cp:1.3.0
2. docker pull kumahq/kuma-dp:1.3.0
3. docker pull kumahq/kumactl:1.3.0
4. docker pull kumahq/kuma-prometheus-sd:1.3.0

Also docker run command is also wrong

```
docker run \
    -p 5681:5681 \
    docker.io/kumahq/kuma-cp: run
```

its failing with 

```
docker: invalid reference format.
See 'docker run --help'.
```

Correct command is 

`docker run -p 5681:5681 docker.io/kumahq/kuma-cp:1.3.0 run`

**Comment by jpeach** [comment]
@Bradamant3 This looks like another case where the tooling missed a version number update?
