### ISSUE TITLE
Update HTTP tokens API reference docmentation

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma-website#553]
The HTTP API reference documentation describes `/tokens`, but `/tokens` is deprecated and the (undocumented) `/tokens/dataplane` and `/tokens/zone-ingress` should be used instead:

https://github.com/kumahq/kuma/blob/9e7e2377d16dbe7dc0275cc7d79c239353e1368c/pkg/tokens/builtin/server/webservice.go#L32-L41

**Comment by lahabana** [comment]
Here: https://kuma.io/docs/1.4.0/documentation/http-api/#dataplane-proxy-tokens
