### ISSUE TITLE
Provide instructions how to run dev server inside a Docker container

### ISSUE THREAD

**Issue by yskopets** [kumahq/kuma-website#59]
### Summary

* I'd like to run dev server inside a Docker container (instead of running it on a host machine)
* so, I start a container with `docker run -ti -p 8080:8080 -v ${PWD}:/source circleci/node bash`
* however, when I run `yarn docs:dev` inside it, I can't access `http://localhost:8080` from the host (apparently, dev server is started on `127.0.0.1:8080` instead of `0.0.0.0:8080`, which makes it inaccessible through standard `docker run -p 8080:8080`)

**Comment by Bradamant3** [comment]
@yskopets we haven't had a chance to address this issue in two years :-( -- and now we're migrating to a different framework for the website. Will add this to the new framework wish list, with thanks!
