### ISSUE TITLE
Missing docs for Dataplane.AdvertisedAddress

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma-website#613]
### Summary

Lack of documentation for https://github.com/kumahq/kuma/pull/2116

**Comment by Bradamant3** [comment]
@lobkovilya can you say more about what's missing? It's documented [here](https://kuma.io/docs/1.4.0/documentation/dps-and-data-model/#zone-ingress) which isn't the easiest place to find it. If you have suggestions, I'd love to hear them. Somewhere in the networking section makes sense -- but that whole part of the docs needs rework too ...

**Comment by lobkovilya** [comment]
@Bradamant3 your link points to `ZoneIngress.Networking.AdvertisedAdress`, but we have the same field in the Dataplane
