### ISSUE TITLE
Improve display and copy pasting of shell commands

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma-website#620]
### What happened?

At the moment, the docs don't make it easy to copy paste shell commands.

Looking at [this example](https://kuma.io/docs/1.4.0/documentation/configuration/#universal-67),  we see _two_ `$` characters.They should always be present [in the source](https://github.com/kumahq/kuma-website/blob/67e46dd051562154d11cb7b88f98a906954d984c/docs/docs/1.4.0/documentation/configuration.md?plain=1#L46-L52) because they delineate a new command/the prompt so we shouldn't prefix the block with one. The copy paste helper removes one `$` but leaves the rest, making it impossible to paste and run the commands.

**Comment by lahabana** [comment]
We need to remove old manually old ones.

**Comment by lahabana** [comment]
I think we won't be able to fix copy-pasting until we move away from vuePress
