### ISSUE TITLE
kuma-cp needs to be started with host networking enabled in order to follow the docs steps

### ISSUE THREAD

**Issue by chris-aeviator** [kumahq/kuma-website#644]
### What happened?

When following along the docker docks, it is suggested to 

```
docker run \
    -p 5681:5681 \
    docker.io/kumahq/kuma-cp:1.4.1 run
```

However, when trying to create a dataplane token, an error is returned

```
Error: Access Denied (action not allowed)
```

In order to have a successful token creation, I will need to set 

```
docker run \
    -p 5681:5681 \
    --network="host" \
    docker.io/kumahq/kuma-cp:1.4.1 run
```

to follow along the steps in the documentation. I guess this is due to the missing authentication (which I cannot really find much info in the docs about)

**Comment by lahabana** [comment]
We should document exec instead of `--network=host`

**Comment by zarkozivanovic** [comment]
Hi guys, I'm trying to configure multi-zone service mesh, where global cp is in kubernetes and one of the zones is running on vm (mix of kubernetes zones and vm zones). I have to generate dataplane tokens for the demo app running on the vm and I'm executing (in the global control plane because of https://github.com/kumahq/kuma/issues/4191):
$ kumactl generate dataplane-token --name=redis > kuma-token-redis
and I'm getting: Error: "Access Denied (action not allowed)"
I'm using kuma 1.5.1. I saw this post and can you tell me how can I run my global control plane (it is in the kubernetes) with option: 
--network="host" 

Br,
Zarko

**Comment by michaelbeaumont** [comment]
@zarkozivanovic This issue is only relevant in the context of the Universal mode docs. If you're running your global CP in kubernetes, your problem lies elsewhere.

How did you setup `kumactl` to authenticate with your global CP? Are you using the admin token?

**Comment by zarkozivanovic** [comment]
Hi Michael,

Thanks for the response. Yes, I'm running global CP in the Kubernetes (minikube actually).
I'm using kubectl port-forward 5681:5681 to access global CP and I did not use admin token to authenticate myself. Do you have any reference doc how to do this?

Br,
Zarko

**Comment by michaelbeaumont** [comment]
@zarkozivanovic You can read the docs for [instructions on using the admin token and creating user tokens](https://kuma.io/docs/1.4.x/security/api-server-auth/#usage).

Note that the example there uses the HTTPS endpoint of the API server which is the most secure way of accessing it.

If you're only trying to test things, you can use the insecure HTTP endpoint (assuming your port-forward `5681:5681` is set up):

```bash
$ ADMIN_TOKEN=$(kubectl get secret admin-user-token -n kuma-system --template={{.data.value}} | base64 -d)
$ kumactl config control-planes add \
  --name global-cp \
  --address http://localhost:5681 \
  --auth-type=tokens \
  --auth-conf token=${ADMIN_TOKEN}
```

**Comment by mangoGoForward** [comment]
> @zarkozivanovic You can read the docs for [instructions on using the admin token and creating user tokens](https://kuma.io/docs/1.4.x/security/api-server-auth/#usage).
> 
> Note that the example there uses the HTTPS endpoint of the API server which is the most secure way of accessing it.
> 
> If you're only trying to test things, you can use the insecure HTTP endpoint (assuming your port-forward `5681:5681` is set up):
> 
> ```shell
> $ ADMIN_TOKEN=$(kubectl get secret admin-user-token -n kuma-system --template={{.data.value}} | base64 -d)
> $ kumactl config control-planes add \
>   --name global-cp \
>   --address http://localhost:5681 \
>   --auth-type=tokens \
>   --auth-conf token=${ADMIN_TOKEN}
> ```


It save me, thanks.

**Comment by michaelbeaumont** [comment]
@lahabana Unfortunately the `kuma-cp` doesn't include a `kumactl` binary so `docker exec` won't work.

**Comment by slonka** [comment]
So there are a couple of options here:

1. use the host network
2. `docker exec` and use `wget` to download the `kumactl` (not great, a user would have to know the version/architecture, construct the url themselves, then tar xz that)
3. Add wget support for our installer and then `docker exec` + `wget -q -O - | VERSION=1.8.1 sh -` and then use `kumactl`
4. `docker exec` and use `wget` to issue API requests (e.g. ```wget -q -O- --post-data='{ "Name": "token-name", "Mesh": "default", "ValidFor": "24h" }' \
  --header='Content-Type:application/json' \
  'http://localhost:5681/tokens/dataplane'```
5. add `kumactl` to `kuma-cp` image
6. some sort of a port-forward hack that would make the request appear like it's coming from localhost

**Comment by slonka** [comment]
I'm going for 2. for now since it seems like the most reasonable way.
