### ISSUE TITLE
Inconsistent menu scroll

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma-website#805]
### What happened?

When hovering over the menu sidebar and scrolling, that should scroll independently of the content. At the moment if I want to see the bottom menu items (Kubernetes annotation reference for example) and am on a long page, I need to scroll all the way to the bottom of the main section's content before the menu bar completes it's scroll to the bottom.

**Comment by johnharris85** [comment]
This looks like it's broken again / regression

**Comment by jakubdyszkiewicz** [comment]
dup of https://github.com/kumahq/kuma-website/issues/1087
