### ISSUE TITLE
Install instructions always default to latest

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma-website#822]
### What happened?

When choosing a specific version of Kuma from the dropdown, the install page always points to latest because that's what the installer.sh script does. We should amend the command to include `VERSION=xxxx` so that running the installer results in the selected version.

**Comment by MustkimKhatik** [comment]
Can one guide me how to do it? I want to be the assignee to this issue.

**Comment by lahabana** [comment]
Sure @MustkimKhatik .

You can see here:

https://github.com/kumahq/kuma-website/blob/987baea1c6a5bd7a8757b2bbfe5988cb858ea3f5/docs/.vuepress/_snippets/install_kumactl.md?plain=1#L8

and here:

https://github.com/kumahq/kuma-website/blob/987baea1c6a5bd7a8757b2bbfe5988cb858ea3f5/docs/.vuepress/_snippets/install_os.md?plain=1#L15

We call the `installer.sh` script that is here: https://github.com/kumahq/kuma-website/blob/master/docs/.vuepress/public/installer.sh

This script can take an ENV_VAR to specify the version to download all our pages are instrumented with frontmatter data `page.latestVersion` see:

https://github.com/kumahq/kuma-website/blob/987baea1c6a5bd7a8757b2bbfe5988cb858ea3f5/docs/.vuepress/config.js#L389

This line was an attempt to do this but the env var is not at the right place:

https://github.com/kumahq/kuma-website/blob/987baea1c6a5bd7a8757b2bbfe5988cb858ea3f5/docs/.vuepress/_snippets/install_kumactl.md?plain=1#L8


It should be:


 `curl -L https://kuma.io/installer.sh | VERSION={{ $page.latestVersion }} bash -`  and the same in `install_os.md`

**Comment by MustkimKhatik** [comment]
Thank you for assigning it to me! I'll be looking into it now.

**Comment by MustkimKhatik** [comment]
Hey @lahabana I've doubt about that ENV_VAR if its included in script file or it has to be manually added?

**Comment by lahabana** [comment]
The VERSION env_var is already in the script. `$page.latestVersion` already exists.

**Comment by MustkimKhatik** [comment]
> The VERSION env_var is already in the script. `$page.latestVersion` already exists.

Yes got it thanks

**Comment by kleinfreund** [comment]
This was fixed in #992 thanks to @MustkimKhatik.

**Comment by MustkimKhatik** [comment]
> This was fixed in #992 thanks to @MustkimKhatik.

Sure. Thank you too, for guiding me!
