### ISSUE TITLE
The copy button moves if the text box contains a horizontal slider

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma-website#867]
### What happened?

<img width="528" alt="image" src="https://user-images.githubusercontent.com/12110261/175512339-834e304f-d75d-41e9-aa89-b6642d3cd642.png">

**Comment by adithyaakrishna** [comment]
@lobkovilya Can I take this up?

**Comment by bartsmykla** [comment]
Definitely, go for it :-)
