### ISSUE TITLE
Installer arch detection failing

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma-website#879]
### What happened?

I recently updated to the new kuma version and it seems that arch detection is failing and the installer downloaded and installed a **x86_64** version of the binary even though I'm running **M1 ARM**.

Steps to reproduce (/ terminal output):
```
$ curl -L https://kuma.io/installer.sh | sh -
# ...

$ kumactl version
Client: Kuma 1.7.0-amd64
Unable to connect to control plane: Get "http://localhost:5681/": dial tcp [::1]:5681: connect: connection refused

$ which kumactl
/Users/krzysztof.slonka@konghq.com/bin//kumactl

$ file /Users/krzysztof.slonka@konghq.com/bin//kumactl
/Users/krzysztof.slonka@konghq.com/bin//kumactl: Mach-O 64-bit executable x86_64
```

AC:
- the installer should correctly detect the OS version and install the appropriate binaries
- this functionality should be tested and hooked up to CI (there is already a smoke test there)

**Comment by michaelbeaumont** [comment]
@lukidzi this was fixed by the above PR, right?
