### ISSUE TITLE
[Bug] - Updated Red Hat Logo and Name

### ISSUE THREAD

**Issue by adithyaakrishna** [kumahq/kuma-website#970]
### What happened?

**Description:**

The Red Hat logo on this page, https://kuma.io/install/latest/ is outdated according to the brand guidelines https://www.redhat.com/en/about/brand/standards/logo and needs to be updated to the new one

<img width="1329" alt="Screenshot 2022-08-19 at 3 07 18 PM" src="https://user-images.githubusercontent.com/23498248/185590920-e37040ea-2930-437e-872b-1bff4c631424.png">

**Comment by jakubdyszkiewicz** [comment]
> Triage: in progress here https://github.com/kumahq/kuma-website/pull/971
