### ISSUE TITLE
[Docs] (not) Duplicate entries - Deploy > Explore w/ demo app(s)

### ISSUE THREAD

**Issue by usrbinkat** [kumahq/kuma-website#991]
### Problem
Kubernetes & Universal "Explore Kuma" sections look like duplicate material at first.

Should consider changing layout / section titles to increase visible differentiators.

![Kuma Docs Duplicate Deploy Entry](https://user-images.githubusercontent.com/54747391/188244083-16719c2b-6f2f-4282-9a8c-c24562f63639.png)

**Comment by MustkimKhatik** [comment]
can we do the highlighted color to the keywords (Kubernetes/Universal) here?

**Comment by jakubdyszkiewicz** [comment]
> Triage: change the titles to `Explore Kuma on Kubernetes` & `Explore Kuma on Universal`

**Comment by MustkimKhatik** [comment]
Hey @jakubdyszkiewicz, can I work on this issue?

**Comment by lahabana** [comment]
@MustkimKhatik sorry it took so long. Yes of course (No need to ask in the future :) )

**Comment by MustkimKhatik** [comment]
> @MustkimKhatik sorry it took so long. Yes of course (No need to ask in the future :) )

Ok sure ✌️

**Comment by slonka** [comment]
Closed via https://github.com/kumahq/kuma-website/pull/1024
