### ISSUE TITLE
Kuma Sidecar (envoy proxy) resource settings

### ISSUE THREAD

**Issue by skaravad** [kumahq/kuma-website#994]
### Summary

Kuma sidecar CPU and Memory requests and limits are global , this should configurable per service via annotations, something like
  ` kuma.io/sidecar-cpu-request`
   `kuma.io/sidecar-cpu-limit`
   `kuma.io/sidecar-mem-request`
   `kuma.io/sidecar-mem-limit`

This will help services which can only scale vertically. If no annotation is provided may be it can default to global setting.

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's add an example in docs how to do this with containerpatch
